services:
  server1:
    build: ./app1
    container_name: fastapi1
    # ports:
    #   - "8001:8000"
    expose:
      - "8000"
  server2:
    build: ./app2
    container_name: fastapi2
    # ports:
    #   - "8002:8000"
    expose:
      - "8000"
  server3:
    build: ./app3
    container_name: fastapi3
    # ports:
    #   - "8003:8000"
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3